import {
  Biokefir,
  Butter,
  CondensedMilk,
  Curd,
  Kefir,
  Milk,
  ProcessedChocolateCheese,
  SourCream,
} from "../assets/img/index.jsx"

export const cartItems = [
  {
    id: 1,
    title: "Молоко",
    width: "240px",
    height: "400.9px",
    colorCard: "#B49FC3",
    image: Milk,
  },
  {
    id: 2,
    width: "240px",
    height: "400.9px",
    colorCard: "#B5CB07",
    image: Biokefir,
  },
  {
    id: 3,
    title: "Масло",
    width: "260px",
    height: "350.9px",
    colorCard: "#D2AF4A",
    image: Butter,
  },
  {
    id: 4,
    title: "Каймак",
    width: "290px",
    height: "190px",
    colorCard: "#A5BADD",
    image: SourCream,
  },
  {
    id: 5,
    title: "Сыр",
    width: "290px",
    height: "190px",
    colorCard: "#9E672D",
    image: ProcessedChocolateCheese,
  },
  {
    id: 6,
    title: "Кефир",
    width: "260px",
    height: "390.9px",
    colorCard: "#F59F9F",
    image: Kefir,
  },
  {
    id: 7,
    title: "Творожный десерт",
    width: "302px",
    height: "303px",
    colorCard: "#4D6895",
    image: Curd,
  },
  {
    id: 8,
    title: "Сгущённое молоко",
    width: "410px",
    height: "410px",
    colorCard: "#37A1C5",
    image: CondensedMilk,
  },
]
